### ISSUE TITLE
Registry name typo in guide book

### ISSUE THREAD

**Issue by ChloeDawn** [copygirl/slime-skies#5]
```
Invalid extra recipe mapping: minecraft:catcus to page 0 in entry patchouli:overworld/04_desert: Unknown item ID: minecraft:catcus
```
https://github.com/copygirl/slime-skies/blob/21b979f3eb781b17cb6c918c4537e6eb599e31ed/patchouli_books/slime_skies_guide/en_us/entries/overworld/04_desert.json#L6

**Comment by copygirl** [comment]
Alternative fix: Add Catcus item.
